services:
  api:
    build: .
    env_file: .env
    environment:
      POSTGRES_SERVER: db # Leave this to point to the service below
      POSTGRES_DB: "" # This is the name of the db you use below
      POSTGRES_PASSWORD: "password" # Password of the db you use below
      REDIS_HOST: redis
    expose:
      - 8000
    command: ["fastapi", "run", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: "postgres" # Leave as is or create your own
      POSTGRES_PASSWORD: "password" # Leave as is or create your own
      POSTGRES_DB: "" # Create a database name
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  
  redis:
    image: redis:8
  
  celery:
    build: .
    command: ["celery", "-A", "app.worker.tasks", "worker", "--loglevel=info"]
    environment:
      REDIS_HOST: redis

  react:
    build:
      context: ../frontend
    ports:
      - "5173:5173"
    env_file:
      - ../frontend/.env
    environment:
      - PORT=5173
    command: ["npm", "run", "start"]
    depends_on:
      - api

volumes:
  postgres_data:

    