"""add user email_verified

Revision ID: 026674fc9e81
Revises: 739dc1ad5c3a
Create Date: 2026-05-23 16:15:30.496896

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "026674fc9e81"
down_revision: Union[str, Sequence[str], None] = "739dc1ad5c3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_users",
        sa.Column("email_verified", sa.Boolean(), nullable=False, server_default='false'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_users", "email_verified")
    # ### end Alembic commands ###
